[WIP]インクリメンタルサーチの実装
autumnleaves111/chat-space pull request #6
Opened 2019-03-21 12:41 UTC by autumnleaves111

#WHAT
インクリメンタルサーチを実装する
#WHY
グループ管理の操作を簡略化するため

2019-03-21 12:51 UTC, autumnleaves111 commented
ユーザー登録および削除のgif動画です。
https://i.gyazo.com/bf95af140091e6d00ac59719fa660c83.gif

2019-03-21 12:57 UTC, yuki-uchida requested changes

2019-03-21 12:57 UTC, yuki-uchida commented on app/assets/javascripts/user.js
> +      .done(function(data) {
dataよりも具体的な名前にしましょう

2019-03-22 02:00 UTC, TOMARUMARU approved these changes
LGTM

2019-03-22 03:54 UTC, merged